<div style="text-align: center;">
    <h1 style="
        background: linear-gradient(135deg, hsla(32, 84%, 25%, 1.00), #fe8c00ff); 
        color: white; 
        padding: 15px 30px; 
        border-radius: 500px; 
        font-family: 'Segoe UI', Arial, sans-serif; 
        box-shadow: 0 4px 15px rgba(0,0,0,0.3);
        display: inline-block;
    ">
        NumPy Exercises
    </h1>
</div>


<h3 style="color:#DC9A3F"><strong>1.Import the numpy package under the name (np)</strong></h3>

In [114]:
import numpy as np

<h3 style="color:#DC9A3F"><strong>2. Print the numpy version and the configuration</strong></h3>

In [115]:
np.__version__

'2.1.3'

<h3 style="color:#DC9A3F"><strong>3. Create a null vector of size 10</strong></h3>

In [116]:
vector = np.zeros(10)

<h3 style="color:#DC9A3F"><strong>4. How to find the memory size of any array </strong></h3>

In [117]:
vector.size * vector.itemsize
vector.__sizeof__() 
vector.nbytes

80

<h3 style="color:#DC9A3F"><strong>5. How to get the documentation of the numpy add function from the command line? </strong></h3>

In [118]:
np.add.__doc__

"add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])\n\nAdd arguments element-wise.\n\nParameters\n----------\nx1, x2 : array_like\n    The arrays to be added.\n    If ``x1.shape != x2.shape``, they must be broadcastable to a common\n    shape (which becomes the shape of the output).\nout : ndarray, None, or tuple of ndarray and None, optional\n    A location into which the result is stored. If provided, it must have\n    a shape that the inputs broadcast to. If not provided or None,\n    a freshly-allocated array is returned. A tuple (possible only as a\n    keyword argument) must have length equal to the number of outputs.\nwhere : array_like, optional\n    This condition is broadcast over the input. At locations where the\n    condition is True, the `out` array will be set to the ufunc result.\n    Elsewhere, the `out` array will retain its original value.\n    Note that if an uninitialized `out` array is created via the defau

<h3 style="color:#DC9A3F"><strong>6. Create a null vector of size 10 but the fifth value which is 1  </strong></h3>

In [119]:
vector=np.zeros(10, dtype=int)
vector[4]=1
vector

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

<h3 style="color:#DC9A3F"><strong>7. Create a vector with values ranging from 10 to 49</strong></h3>

In [120]:
vector=np.array(np.arange(10, 50))
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

<h3 style="color:#DC9A3F"><strong>8. Reverse a vector (first element becomes last)</strong></h3>

In [121]:
vector=vector[::-1]
vector 

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

<h3 style="color:#DC9A3F"><strong>9. Create a 3x3 matrix with values ranging from 0 to 8</strong></h3>

In [122]:
matrix = np.arange(0, 9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<h2 style="color:#DC9A3F; display:inline;">
  <strong>10. Find indices of non-zero elements from  </strong>
</h2>
<h3 style="color:#F9F7FA; display:inline; margin-left:8px;">
[1,2,0,0,4,0] 
</h3>


In [123]:
vector = np.array([1,2,0,0,4,0])
x=np.where(vector != 0)
x[0]

array([0, 1, 4])

<h3 style="color:#DC9A3F"><strong>11. Create a 3x3 identity matrix</strong></h3>

In [124]:
matrix = np.eye(3)
matrix.astype(int)   

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

<h3 style="color:#DC9A3F"><strong>12. Create a 3x3x3 array with random values</strong></h3>

In [125]:
array = np.random.random((3, 3, 3))
array.shape
array


array([[[0.01754051, 0.81718176, 0.71337807],
        [0.15377898, 0.37128277, 0.89106019],
        [0.38166578, 0.5149362 , 0.44437885]],

       [[0.77934554, 0.09028204, 0.48356479],
        [0.99467449, 0.48359403, 0.58789246],
        [0.67652167, 0.54218701, 0.21268669]],

       [[0.1857741 , 0.06182152, 0.46627486],
        [0.85226638, 0.62940572, 0.63755753],
        [0.75043218, 0.2785238 , 0.38007956]]])

<h3 style="color:#DC9A3F"><strong>13. Create a 10x10 array with random values and find the minimum and maximum values</strong></h3>

In [126]:
array=np.random.random((10,10))
x=np.max(array).astype(float)
y=np.min(array).astype(float)
print(f'the max value is {x} and the min value is {y}')

the max value is 0.9955760522615109 and the min value is 0.002463411166507168


<h3 style="color:#DC9A3F"><strong>14. Create a random vector of size 30 and find the mean value</strong></h3>

In [127]:
vector=np.random.random(30)
np.mean(vector)

np.float64(0.4980006915134643)

<h3 style="color:#DC9A3F"><strong>15. Create a 2d array with 1 on the border and 0 inside</strong></h3>

In [128]:
vector=np.ones((5,5)).astype(int)
vector[1:-1,1:-1]=0
vector

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

<h3 style="color:#DC9A3F"><strong>16. How to add a border (filled with 0's) around an existing array? </strong></h3>

In [129]:
vector = np.array([1,2,9,2,1,2,3,4,3,4])
zeros = np.zeros((3,len(vector)+2))
zeros[1,1:-1] = vector
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 2., 9., 2., 1., 2., 3., 4., 3., 4., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

<h3 style="color:#DC9A3F"><strong>17. What is the result of the following expression? </strong></h3>
<h4 style="color:#D20103; display:inline;"><strong>(0 * np.nan) </strong></h4><h4 style="color:#7DDA58; display:inline; margin-left:8px;">Answer is : NaN</h4>
<br>
<h4 style="color:#D20103; display:inline;"><strong>(np.nan == np.nan) </strong></h4><h4 style="color:#7DDA58; display:inline; margin-left:8px;">Answer is : False</h4>
<br>
<h4 style="color:#D20103; display:inline;"><strong>(np.inf > np.nan)</strong></h4><h4 style="color:#7DDA58; display:inline; margin-left:8px;">Answer is : False</h4>
<br>
<h4 style="color:#D20103; display:inline;"><strong>(np.nan - np.nan)</strong></h4><h4 style="color:#7DDA58; display:inline; margin-left:8px;">Answer is : NaN</h4>
<br>
<h4 style="color:#D20103; display:inline;"><strong>(np.nan in set([np.nan]))</strong></h4><h4 style="color:#7DDA58; display:inline; margin-left:8px;">Answer is : True</h4>
<br>
<h4 style="color:#D20103; display:inline;"><strong>(0.3 == 3 * 0.1)</strong></h4><h4 style="color:#7DDA58; display:inline; margin-left:8px;">Answer is : False</h4>


<h3 style="color:#DC9A3F"><strong>18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal </strong></h3>

In [131]:
Z = np.diag(np.arange(1,5),k=-1)
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

<h3 style="color:#DC9A3F"><strong> 19. Create a 8x8 matrix and fill it with a checkerboard pattern </strong></h3>

In [132]:
matrix = np.random.randint(0,1,(8,8))
matrix[1::2,::2] = 1
matrix[::2,1::2] = 1
matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

<h3 style="color:#DC9A3F"><strong> 21. Create a checkerboard 8x8 matrix using the tile function</strong></h3>

In [133]:
np.tile([[0, 1], [1, 0]], (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

<h3 style="color:#DC9A3F"><strong> 22. Normalize a 5x5 random matrix knowing normalization = (x-min/max-min )</strong></h3>

In [134]:
matrix = np.random.random((5, 5))
Nmatrix = (matrix - np.mean(matrix)) / np.std(matrix)
Nmatrix


array([[ 0.24497097, -0.69420283,  1.58691344, -1.11610067,  0.1035904 ],
       [ 0.52546224, -1.37663361,  0.16239112, -0.81272554, -0.30067969],
       [ 0.49466934,  1.17159078,  1.63069194, -0.44323156,  1.50363655],
       [-0.1391999 , -1.37053579,  0.99444101, -1.27116936, -0.72572811],
       [-1.48222964, -0.97296293,  0.16540126,  1.58525705,  0.53638355]])

<h3 style="color:#DC9A3F"><strong> 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) </strong></h3>

In [135]:
a = np.ones((5,3))
b = np.ones((3,2))
a@b

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

<h3 style="color:#DC9A3F"><strong> 25. Given a 1D array, negate all elements which are between 3 and 8, in place. </strong></h3>

In [136]:
array = np.arange(11)
array[(3 < array) & (array < 8)] *= -1
array

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

<h3 style="color:#DC9A3F"><strong> 28. What are the result of the following expressions? </strong></h3>

<h4 style="color:#D20103; display:inline;"><strong>a) np.array(0) / np.array(0) </strong></h4><h4 style="color:#7DDA58; display:inline; margin-left:8px;">Answer is : NaN</h4>
<br>
<h4 style="color:#D20103; display:inline;"><strong>b) np.array(0) // np.array(0) </strong></h4><h4 style="color:#7DDA58; display:inline; margin-left:8px;">Answer is : 0</h4>
<br>
<h4 style="color:#D20103; display:inline;"><strong>c) np.array([np.nan]).astype(int).astype(float) </strong></h4><h4 style="color:#7DDA58; display:inline; margin-left:8px;">Answer is : [0.0]</h4>


<h3 style="color:#DC9A3F"><strong> 30. How to find common values between two arrays? </strong></h3>

In [137]:
a = np.arange(0,20)
b = np.arange(5,15)
np.intersect1d(a,b)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

<h3 style="color:#DC9A3F"><strong> 32. Is the following expressions true? </strong></h3>
<h4 style="color:#D20103; display:inline;"><strong>np.sqrt(-1) == np.emath.sqrt(-1)</strong></h4><h4 style="color:#7DDA58; display:inline; margin-left:8px;">Answer is : False</h4>




<h3 style="color:#DC9A3F"><strong> 33. How to get the dates of yesterday, today and tomorrow? </strong></h3>

In [145]:
today = np.datetime64('today')
yesterday = today - np.timedelta64(1, 'D')
tomorrow  = today + np.timedelta64(1, 'D')
c = np.concatenate([[yesterday],[today],[tomorrow]])
c

array(['2025-08-13', '2025-08-14', '2025-08-15'], dtype='datetime64[D]')

<h3 style="color:#DC9A3F"><strong> 34. How to get all the dates corresponding to the month of July 2016?</strong></h3>

In [146]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
dates

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

<h3 style="color:#DC9A3F"><strong> 35. How to compute ((A+B)*(-A/2)) in place (without copy)?</strong></h3>

In [147]:
A = np.array([1,2,3,4], dtype='float64')
B = np.array([1,1,1,1], dtype='float64')
np.multiply(np.add(A,B,out=B), np.divide(np.negative(A,out=A),2,out=A),out=A)

array([ -1.,  -3.,  -6., -10.])

<h3 style="color:#DC9A3F"><strong> 36. Extract the integer part of a random array of positive numbers using 4 different methods</strong></h3>

In [150]:
arr = np.random.random(5) * 10
arr1 = np.floor(arr)
arr2 = np.trunc(arr)
arr3 = np.fix(arr)
arr4 = arr.astype(int)
c = np.concatenate([[arr1],[arr2],[arr3],[arr4]])
c

array([[7., 8., 5., 5., 1.],
       [7., 8., 5., 5., 1.],
       [7., 8., 5., 5., 1.],
       [7., 8., 5., 5., 1.]])

<h3 style="color:#DC9A3F"><strong> 37. Create a 5x5 matrix with row values ranging from 0 to 4</strong></h3>

In [152]:
matrix = np.tile(np.arange(5),5).reshape((5,5))
matrix

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

<h3 style="color:#DC9A3F"><strong>38. Consider a generator function that generates 10 integers and use it to build an array</strong></h3>

In [153]:
np.random.randint(0,100,10)

array([87, 23, 35, 98, 43, 43, 80, 72, 49, 51], dtype=int32)

<h3 style="color:#DC9A3F"><strong>39. Create a vector of size 10 with values ranging from 0 to 1, both excluded</strong></h3>

In [154]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

<h3 style="color:#DC9A3F"><strong>40. Create a random vector of size 10 and sort it</strong></h3>

In [155]:
vector=np.random.random(10)
np.sort(vector)

array([0.04383626, 0.04638803, 0.2328896 , 0.34558545, 0.5596372 ,
       0.64391421, 0.69584484, 0.75747171, 0.84764776, 0.87725624])

<h3 style="color:#DC9A3F"><strong>41. How to sum a small array faster than np.sum? </strong></h3>

In [157]:
array=np.array([1,2,3,4])
int(np.add.reduce(array))

10

<h3 style="color:#DC9A3F"><strong>42. Consider two random array A and B, check if they are equal</strong></h3>

In [177]:
A = np.random.randint(0,2,1)
B = np.random.randint(0,2,1)
ok = np.allclose(A,B)
print(ok)

False


<h3 style="color:#DC9A3F"><strong> 45. Create random vector of size 10 and replace the maximum value by 0</strong></h3>

In [178]:
vector = np.random.random(10)
vector[vector.argmax()] = 0
vector

array([0.53281359, 0.57611157, 0.49945857, 0.65550022, 0.        ,
       0.07456703, 0.06218242, 0.48401219, 0.17261384, 0.87925122])

<h3 style="color:#DC9A3F"><strong> 49. How to print all the values of an array?</strong></h3>

In [181]:
array = np.arange(200)
np.set_printoptions(threshold=np.inf)
array


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

<h3 style="color:#DC9A3F"><strong> 50. How to find the closest value (to a given scalar) in a vector?</strong></h3>

In [ ]:
array = np.random.randint(0,100,100)
isearch = 5.75
array[np.argmin(np.abs(isearch - array))]


np.int32(6)