# What is NumPy?

**1- NumPy is a Python library used for working with arrays.**

**2- It also has functions for working in domain of linear algebra, fourier transform, and matrices.**

**3- NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.**

**4- NumPy stands for Numerical Python.**

**5- It uses Basic Linear Algebra Subprograms (BLAS) is a collection of high performance functions that provide basic tools for linear algebra related tasks.**

**6- NumPy is a python library and is written partially in Python, but most of the parts that require fast computations are written in C , C++ and Fortran.**

# Why Use NumPy?

**1- In Python we have lists that serve the purpose of arrays, but they are slow to process.**

**2- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.**

**3- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.**

**4- Arrays are very frequently used in data science, where speed and resources are very important.**

# Lets Start =>

In [28]:
import numpy as np

## 1) Intro to NumPy

In [30]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
np1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
np1.shape

(12,)

In [33]:
np.size(np1)

12

In [35]:
np2=np.arange(12)
np2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
np3=np.arange(5,18,2)
np3

array([ 5,  7,  9, 11, 13, 15, 17])

In [39]:
np4 = np.zeros(10)
np4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
np5 = np.zeros((2,10))
np5

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [42]:
np6 = np.full((10),6)
np6
print(np6.shape)

(10,)


In [43]:
np7 = np.full((2,10),6)
np7

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6]])

In [44]:
my_lst = [1,2,3,4,5,6,7,8,9,10]
np8 = np.array(my_lst)
np8

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
np9 = np.ones((2,10))
np9

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## 2) Indexing & Slicing Numpy Arrays

In [47]:
np1 = np.array([1,2,3,4,5,6,7,8,9])

In [22]:
#1-D array

In [48]:
np1[1:5]

array([2, 3, 4, 5])

In [49]:
np1[3:]

array([4, 5, 6, 7, 8, 9])

In [50]:
np1[-3:-1]

array([7, 8])

In [51]:
np1[1:5:2]

array([2, 4])

In [53]:
np1[2]

3

In [23]:
#2D array

In [54]:
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [55]:
np2[1,2]

8

In [56]:
np2[0:1,1:3]

array([[2, 3]])

In [57]:
np2[0:2,1:3]

array([[2, 3],
       [7, 8]])

## 3) Numpy Universal Functions

In [61]:
np1 = np.array([0,1,2,3,4,5,6,7,8,9,-100])

In [59]:
#square root of each element
print(np.sqrt(np1))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [62]:
#absoulute value
print(np.absolute(np1))

[  0   1   2   3   4   5   6   7   8   9 100]


In [63]:
#exponentials
np.exp(np1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 3.72007598e-44])

In [65]:
#min max
print(np.max(np1))
print(np.min(np1))

9
-100


In [66]:
#sign positive or negative
np.sign(np1)

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1])

In [68]:
#Trig sin cos log
print(np.sin(np1))
print(np.cos(np1))
print(np.log(np1))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849  0.50636564]
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026  0.86231887]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458        nan]


/tmp/ipykernel_15895/3860036235.py:4: RuntimeWarning: divide by zero encountered in log
  print(np.log(np1))
/tmp/ipykernel_15895/3860036235.py:4: RuntimeWarning: invalid value encountered in log
  print(np.log(np1))


## 4) NumPy Array Copy vs. View

In [84]:
np1 = np.array([0,1,2,3,4,5])

In [70]:
#create a view
np2 = np1.view()

In [71]:
np1

array([0, 1, 2, 3, 4, 5])

In [72]:
np2

array([0, 1, 2, 3, 4, 5])

In [73]:
np1[0]=41

In [74]:
np1

array([41,  1,  2,  3,  4,  5])

In [75]:
np2

array([41,  1,  2,  3,  4,  5])

In [85]:
#create a copy
np2 = np1.copy()

In [86]:
np1

array([0, 1, 2, 3, 4, 5])

In [87]:
np2

array([0, 1, 2, 3, 4, 5])

In [81]:
np1[0] = 41

In [82]:
np1

array([41,  1,  2,  3,  4,  5])

In [83]:
np2

array([0, 1, 2, 3, 4, 5])

In [88]:
np2[0] = 41

In [89]:
np1

array([0, 1, 2, 3, 4, 5])

In [90]:
np2

array([41,  1,  2,  3,  4,  5])

## 5) Shape & Reshape NumPy

In [91]:
#create 1-D Numpy array and get the shape
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
np1.shape

(12,)

In [93]:
#create 2-D array and get the shape
np2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(np2)
print(np2.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [96]:
#reshape 2-D
np3 = np1.reshape(3,4)
print(np3)
print(np3.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [97]:
#reshape 3-D
np4 = np1.reshape(2,3,2)
print(np4)
print(np4.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [100]:
#flatten to 1-D
np5 = np4.reshape(-1)
print(np5)
print(np5.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


## 6) Iterating Though Numpy

In [101]:
#1-D
np1 = np.array([1,2,3,4,5,6,7,8,9,10])
for x in np1:
    print(x)

1
2
3
4
5
6
7
8
9
10


In [102]:
#2-D
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in np2:
    print(x)     #print rows
    for y in x:
        print(y)

[1 2 3 4 5]
1
2
3
4
5
[ 6  7  8  9 10]
6
7
8
9
10


In [106]:
#3-D
np3 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
for x in np3:
    print(x)
    for y in x:
        print(y)
        for z in y:
            print(z)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
1
2
3
4
[5 6 7 8]
5
6
7
8
[ 9 10 11 12]
9
10
11
12


In [107]:
#summerizing
#use np.nditer()

for x in np.nditer(np3):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


## 7) Sorting NumPy Arrays

In [108]:
#numerical
np1 = np.array([6,7,4,9,0,2,1])
print(np.sort(np1))

[0 1 2 4 6 7 9]


In [109]:
#alphabitical
np2 = np.array(["ali", "Tamer", "Ahmed", "Noura"])
print(np2)
print(np.sort(np2))

['ali' 'Tamer' 'Ahmed' 'Noura']
['Ahmed' 'Noura' 'Tamer' 'ali']


In [110]:
np3 = np.array([True, False, False, True])
print(np3)
print(np.sort(np3))

[ True False False  True]
[False False  True  True]


In [113]:
print(np1)
print(np.sort(np1))
sorted_np1 = np.sort(np1)
print(np1)
print(sorted_np1)

[6 7 4 9 0 2 1]
[0 1 2 4 6 7 9]
[6 7 4 9 0 2 1]
[0 1 2 4 6 7 9]


In [116]:
#2-D
np4 = np.array([[6,7,1,9],[8,3,5,0]])
print(np4)
print("**********")
print(np.sort(np4))

[[6 7 1 9]
 [8 3 5 0]]
**********
[[1 6 7 9]
 [0 3 5 8]]


## 8) Searching NumPy Arrays

In [119]:
np1 = np.array([1,2,3,10,3])
x = np.where(np1 == 10)
print(np1)
print(x)
print(x[0])
print(np1[x[0]])

[ 1  2  3 10  3]
(array([3]),)
[3]
[10]


In [121]:
y = np.where(np1%2==1)
print(np1)
print(y[0])

[ 1  2  3 10  3]
[0 2 4]


## 9) How to Filter NumPy Arrays

In [125]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10])
x = [True,True, False, True, False, False, False, True, True, True]
print(np1)
print(x)
print(np1[x])
print(np1)

[ 1  2  3  4  5  6  7  8  9 10]
[True, True, False, True, False, False, False, True, True, True]
[ 1  2  4  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [126]:
filtered_lst = []
for values in np1:
    if values % 2 ==0:
        filtered_lst.append(True)
    else:
        filtered_lst.append(False)

print(np1)
print(filtered_lst)
print(np1[filtered_lst])

[ 1  2  3  4  5  6  7  8  9 10]
[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]


## 10) Other functions

transpose()

ravel() = reshape(-1)

print(a.sum())

print(a.max())

print(a.min())

print(a.argmax())

print(a.argmin())

print(a.mean())

print(a.std())

In [127]:
a = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [128]:

# Transposing the array
a_transposed = a.transpose()
print(a_transposed)


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [130]:

# Flattening the array using ravel()
a_raveled = a.ravel()
print(a_raveled)

a_flatten = a.flatten()
print(a_flatten)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [131]:

# Flattening the array using reshape(-1)
a_reshaped = a.reshape(-1)
print(a_reshaped)



[1 2 3 4 5 6 7 8 9]


In [132]:
# Sum of all elements in the array
sum_a = a.sum()
print(sum_a)


45


In [133]:

# Maximum value in the array
max_a = a.max()
print(max_a)



9


In [134]:
# Minimum value in the array
min_a = a.min()
print(min_a)



1


In [135]:
# Index of the maximum value
argmax_a = a.argmax()
print(argmax_a)



8


In [136]:
# Index of the minimum value
argmin_a = a.argmin()
print(argmin_a)



0


In [137]:
# Mean of all elements in the array
mean_a = a.mean()
print(mean_a)


5.0


In [138]:

# Standard deviation of the array
std_a = a.std()
print(std_a)


2.581988897471611


## Resources:

https://www.youtube.com/watch?v=gBd5cg5ELN0&list=PLCC34OHNcOtpalASMlX2HHdsLNipyyhbK&index=9
https://www.w3schools.com/python/numpy/numpy_intro.asp